### ISSUE TITLE
Cannot Backup To Backupdir If Set

### ISSUE THREAD

**Issue by gangsterofboats** [lhmouse/nano-win#19]
If backupdir is set to, I think, any Windows path, Nano cannot backup to that path, but will write to the Home directory instead.  Looking at the source, though not really being good at C, I think the problem lies about lines 1420 to 1430 in the files.c file.  It only replaces the slashes in the path, but Windows also cannot have colons in filenames.

**Comment by lhmouse** [comment]
There are actually a few more issues on this:

1. `get_full_path()` should return a path with forwardslashes instead of backslashes (note other code doesn't check for forwardslashes at all).
2. When checking for relative paths, `dirname[0] != '/'` does not work on Windows. `PathIsRelativeA()` is suggested.
3. Not only are colons disallowed, but also `<>:"/\|?*`, as well as all control characters.

I am working on a fix at the moment.

**Comment by lhmouse** [comment]
Fixed and uploaded:  https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-gef33c2a8.7z

**Comment by gangsterofboats** [comment]
Thanks.

**Comment by lhmouse** [comment]
The previous build may crash or hang if the `backupdir` is set to a path ending with a slash (forward or backward). A new build has been uploadad:  https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-g8ad13081.7z
