### ISSUE TITLE
Why is --noconvert CLI parameter/rc option not respected?

### ISSUE THREAD

**Issue by garoto** [lhmouse/nano-win#9]
I've read your readme.md entrie where you wrote: `+ UNIX style end-of-line handling by default.` 

And I have no issue with it being a default, but I'm wondering what's the rationale on why can't I override it either via CLI argument or via a .nanorc `set noconvert` option, but still able to choose CRLF line-endings with `M-D` when saving a file.

**Comment by lhmouse** [comment]
On Windows the function `open()` opens file in **text mode** by default. This means that if you try saving a file in MS-DOS format, **nano** will add a `CR` before every `LF`, but the CRT inserts another `CR` before every `LF`, resulting lines that end with `CR CR LF`. (By default however, **nano** does not insert `CR` because UNIX EOL is the default, while the CRT still adds a `CR` so you get MS-DOS EOLs, which 'works' by accident.)

 Please refer to nano's authors for the precise description of `noconvert`; I have no idea about it.

**Comment by garoto** [comment]
Wow, quite complicated but I think I managed to finally get the gist of your answer rationale. And just to clear: by CRT you mean the microsoft "C RunTime"?

**Comment by garoto** [comment]
But following up while trying to understand this fully: if I open a `CRLF` termindated file in your `nano` compile, and then press `CTRL+s`, it'll override the orginal line-endings with `LF` chars. 

That's highly annoying, but it's somewhat alright and I'll be ok with this behavior if this final position about this line-endings shenanigans.
